"use client";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {Check,ChevronRight,Dumbbell,BookOpen,Flame,Home,Plus,Target,Trash2,Trophy,LogOut,LoaderCircle,Mail,Lock,Timer,Library,Sunrise,Brain,Play,BarChart3} from "lucide-react";
import {supabase} from "../lib/supabase";

type Task={id:string;title:string;completed:boolean;area:string|null};
type Workout={id:string;title:string;completed:boolean;duration_minutes:number|null};
type Exercise={id:string;workout_id:string;name:string;sets:number|null;reps:string|null;weight_kg:number|null;completed:boolean};
type Book={id:string;title:string;author:string|null;total_pages:number|null;current_page:number;status:string};
type Focus={id:string;duration_minutes:number;intention:string|null;completed_at:string};
const starter=[["Entrenamiento / fútbol","FOOTBALL"],["Estudiar 45 minutos","STUDY"],["Ducha fría","LIFE"],["Leer 10 páginas","LIFE"]];

export default function App(){
 const [tab,setTab]=useState("Hoy"),[tasks,setTasks]=useState<Task[]>([]),[input,setInput]=useState(""),[user,setUser]=useState<any>(null),[loading,setLoading]=useState(true);
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[authMsg,setAuthMsg]=useState(""),[authMode,setAuthMode]=useState<"login"|"signup">("login");
 const [workouts,setWorkouts]=useState<Workout[]>([]),[exercises,setExercises]=useState<Exercise[]>([]),[gymTitle,setGymTitle]=useState("Fuerza + potencia"),[exerciseName,setExerciseName]=useState("");
 const [books,setBooks]=useState<Book[]>([]),[bookTitle,setBookTitle]=useState(""),[focus,setFocus]=useState<Focus[]>([]),[focusMin,setFocusMin]=useState(45),[focusIntent,setFocusIntent]=useState("Universae"),[alarm,setAlarm]=useState("07:00"),[energy,setEnergy]=useState(7); const [sleep,setSleep]=useState(8),[mood,setMood]=useState(7),[checkSaved,setCheckSaved]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setUser(data.session?.user??null);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(user){loadTasks();loadGym();loadLife()}},[user]);
 async function loadLife(){const [{data:b},{data:f},{data:s}]=await Promise.all([supabase.from("books").select("id,title,author,total_pages,current_page,status").order("created_at",{ascending:false}),supabase.from("focus_sessions").select("id,duration_minutes,intention,completed_at").order("completed_at",{ascending:false}).limit(20),supabase.from("user_settings").select("alarm_time,readiness").eq("user_id",user.id).maybeSingle()]);setBooks(b??[]);setFocus(f??[]);if(s?.alarm_time)setAlarm(String(s.alarm_time).slice(0,5));if(s?.readiness)setEnergy(s.readiness);const today=new Date().toISOString().slice(0,10);const {data:ci}=await supabase.from("daily_checkins").select("energy,sleep_hours,mood").eq("checkin_date",today).maybeSingle();if(ci){setEnergy(ci.energy??7);setSleep(Number(ci.sleep_hours??8));setMood(ci.mood??7);setCheckSaved(true)}}
 async function addBook(){if(!bookTitle.trim())return;const {data}=await supabase.from("books").insert({user_id:user.id,title:bookTitle.trim(),status:"reading"}).select("id,title,author,total_pages,current_page,status").single();if(data)setBooks([data,...books]);setBookTitle("")}
 async function logPages(b:Book){const n=Number(prompt("¿En qué página vas?",String(b.current_page)));if(!Number.isFinite(n)||n<0)return;const status=b.total_pages&&n>=b.total_pages?"finished":b.status;await supabase.from("books").update({current_page:n,status,finished_at:status==="finished"?new Date().toISOString().slice(0,10):null}).eq("id",b.id);setBooks(books.map(x=>x.id===b.id?{...x,current_page:n,status}:x))}
 async function addFocus(){const {data}=await supabase.from("focus_sessions").insert({user_id:user.id,duration_minutes:focusMin,intention:focusIntent}).select("id,duration_minutes,intention,completed_at").single();if(data)setFocus([data,...focus])}
 async function saveSettings(){await supabase.from("user_settings").upsert({user_id:user.id,alarm_time:alarm,readiness:energy},{onConflict:"user_id"})}
 async function saveCheckin(){await supabase.from("daily_checkins").upsert({user_id:user.id,checkin_date:new Date().toISOString().slice(0,10),energy,sleep_hours:sleep,mood},{onConflict:"user_id,checkin_date"});setCheckSaved(true)} async function loadGym(){const today=new Date().toISOString().slice(0,10);const {data:w}=await supabase.from("workouts").select("id,title,completed,duration_minutes").eq("workout_date",today).order("created_at");setWorkouts(w??[]);if(w?.length){const ids=w.map(x=>x.id);const {data:e}=await supabase.from("workout_exercises").select("id,workout_id,name,sets,reps,weight_kg,completed").in("workout_id",ids).order("position");setExercises(e??[])}else setExercises([])}
 async function createWorkout(){if(!gymTitle.trim())return;const {data}=await supabase.from("workouts").insert({user_id:user.id,title:gymTitle.trim(),kind:"GYM",workout_date:new Date().toISOString().slice(0,10),duration_minutes:60}).select("id,title,completed,duration_minutes").single();if(data)setWorkouts([...workouts,data])}
 async function addExercise(workoutId:string){if(!exerciseName.trim())return;const {data}=await supabase.from("workout_exercises").insert({user_id:user.id,workout_id:workoutId,name:exerciseName.trim(),sets:3,reps:"8-10",position:exercises.filter(e=>e.workout_id===workoutId).length}).select("id,workout_id,name,sets,reps,weight_kg,completed").single();if(data)setExercises([...exercises,data]);setExerciseName("")}
 async function toggleExercise(e:Exercise){const completed=!e.completed;setExercises(exercises.map(x=>x.id===e.id?{...x,completed}:x));await supabase.from("workout_exercises").update({completed}).eq("id",e.id)}
 async function editExercise(e:Exercise){const sets=Number(prompt("Series",String(e.sets??3)));if(!Number.isFinite(sets)||sets<1)return;const reps=prompt("Repeticiones",e.reps??"8-10");if(reps===null)return;const weight=Number(prompt("Peso en kg",String(e.weight_kg??0)));if(!Number.isFinite(weight)||weight<0)return;await supabase.from("workout_exercises").update({sets,reps,weight_kg:weight}).eq("id",e.id);setExercises(exercises.map(x=>x.id===e.id?{...x,sets,reps,weight_kg:weight}:x))} async function finishWorkout(w:Workout){const completed=!w.completed;setWorkouts(workouts.map(x=>x.id===w.id?{...x,completed}:x));await supabase.from("workouts").update({completed}).eq("id",w.id)}
 async function loadTasks(){const today=new Date().toISOString().slice(0,10);const {data}=await supabase.from("daily_tasks").select("id,title,completed,area").eq("task_date",today).order("position");if(data?.length)setTasks(data);else{const rows=starter.map(([title,area],i)=>({user_id:user.id,client_key:"starter-"+today+"-"+i,title,area,task_date:today,position:i}));const {data:fresh}=await supabase.from("daily_tasks").insert(rows).select("id,title,completed,area");setTasks(fresh??[])}}
 async function auth(){setAuthMsg("");const fn=authMode==="login"?supabase.auth.signInWithPassword({email,password}):supabase.auth.signUp({email,password});const {error}=await fn;if(error)setAuthMsg(error.message);else if(authMode==="signup")setAuthMsg("Cuenta creada. Si recibes un correo de confirmación, confírmalo y vuelve aquí.")}
 async function toggle(t:Task){const completed=!t.completed;setTasks(tasks.map(x=>x.id===t.id?{...x,completed}:x));await supabase.from("daily_tasks").update({completed}).eq("id",t.id)}
 async function add(){if(!input.trim())return;const today=new Date().toISOString().slice(0,10);const {data}=await supabase.from("daily_tasks").insert({user_id:user.id,client_key:"custom-"+crypto.randomUUID(),title:input.trim(),area:"LIFE",task_date:today,position:tasks.length}).select("id,title,completed,area").single();if(data)setTasks([...tasks,data]);setInput("")}
 async function remove(id:string){setTasks(tasks.filter(x=>x.id!==id));await supabase.from("daily_tasks").delete().eq("id",id)}
 const done=tasks.filter(t=>t.completed).length,pct=tasks.length?Math.round(done/tasks.length*100):0;
 if(loading)return <main className="auth"><LoaderCircle className="spin"/><p>Preparando LOCKED IN…</p></main>;
 if(!user)return <main className="auth"><div className="authLogo"><p className="eyebrow">LOCKED IN</p><h1>Tu disciplina.<br/>En un solo sitio.</h1><p className="muted">Entra para sincronizar tu progreso en todos tus dispositivos.</p></div><div className="authBox"><label><Mail size={17}/><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label><Lock size={17}/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&auth()}/></label><button className="primary" onClick={auth}>{authMode==="login"?"Entrar":"Crear cuenta"}</button>{authMsg&&<p className="authMsg">{authMsg}</p>}<button className="link" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"No tengo cuenta — crear una":"Ya tengo cuenta — entrar"}</button></div></main>;
 return <main className="shell"><header><div><p className="eyebrow">LOCKED IN</p><h1>{tab==="Hoy"?"Buenos días, Alex.":tab}</h1><p className="muted">{tab==="Hoy"?"Haz que hoy cuente.":sub(tab)}</p></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/></button></header>
 {tab==="Hoy"&&<><section className="hero"><div><span>PROGRESO DE HOY</span><strong>{pct}%</strong><small>{done} de {tasks.length} completadas</small></div><div className="ring" style={{"--p":pct} as CSSProperties}><b>{pct}</b></div></section><Title done={done} total={tasks.length}/><TaskList tasks={tasks} toggle={toggle}/><Adder input={input} setInput={setInput} add={add}/><div className="grid"><Card icon={<Dumbbell/>} title="Gym" text="Entrenamiento y progreso"/><Card icon={<BookOpen/>} title="Estudio" text="Sesiones y objetivos"/><Card icon={<Target/>} title="Disciplina" text="Hábitos y constancia"/><Card icon={<Trophy/>} title="Progreso" text={pct+"% completado hoy"}/></div></>}
 {tab==="Hábitos"&&<><Title done={done} total={tasks.length}/><section className="list">{tasks.map(t=><article className={"task "+(t.completed?"done":"")} key={t.id}><button className="check" onClick={()=>toggle(t)}>{t.completed&&<Check size={15}/>}</button><div onClick={()=>toggle(t)}><b>{t.title}</b><small>{t.area}</small></div><button className="delete" onClick={()=>remove(t.id)}><Trash2 size={17}/></button></article>)}</section><Adder input={input} setInput={setInput} add={add}/></>}
 {tab==="Gym"&&<section className="gymPanel"><div className="sectionTitle"><h2>Entrenamiento de hoy</h2><span>{workouts.length} sesión{workouts.length===1?"":"es"}</span></div>{workouts.length===0?<div className="createWorkout"><Dumbbell size={36}/><h2>¿Qué toca hoy?</h2><p>Crea tu sesión y registra cada ejercicio.</p><input value={gymTitle} onChange={e=>setGymTitle(e.target.value)} placeholder="Nombre del entrenamiento"/><button className="primary" onClick={createWorkout}>Crear entrenamiento</button></div>:workouts.map(w=><article className={"workout "+(w.completed?"workoutDone":"")} key={w.id}><div className="workoutHead"><div><small>SESIÓN DE HOY</small><h2>{w.title}</h2><p>{w.duration_minutes??60} min · {exercises.filter(e=>e.workout_id===w.id&&e.completed).length}/{exercises.filter(e=>e.workout_id===w.id).length} ejercicios</p></div><button className="check big" onClick={()=>finishWorkout(w)}>{w.completed&&<Check/>}</button></div><div className="exerciseList">{exercises.filter(e=>e.workout_id===w.id).map(e=><div className={"exercise "+(e.completed?"done":"")} key={e.id} onClick={()=>toggleExercise(e)} onDoubleClick={()=>editExercise(e)}><button className="check">{e.completed&&<Check size={14}/>}</button><div><b>{e.name}</b><small>{e.sets??3} series · {e.reps??"8-10"} reps{e.weight_kg?" · "+e.weight_kg+" kg":""}<em> · doble toque para editar</em></small></div></div>)}</div><div className="add"><input value={exerciseName} onChange={e=>setExerciseName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addExercise(w.id)} placeholder="Añadir ejercicio..."/><button onClick={()=>addExercise(w.id)}><Plus/></button></div></article>)}</section>}
 {tab==="Estudio"&&<section><div className="sectionTitle"><h2>Focus</h2><span>{focus.reduce((a,x)=>a+x.duration_minutes,0)} min registrados</span></div><div className="focusBox"><Brain/><div><b>Sesión de concentración</b><small>Define el objetivo y registra un bloque sin distracciones.</small></div><input value={focusIntent} onChange={e=>setFocusIntent(e.target.value)} placeholder="¿Qué vas a estudiar?"/><div className="focusRow"><input type="number" min="5" max="240" value={focusMin} onChange={e=>setFocusMin(Number(e.target.value))}/><span>min</span><button className="primary" onClick={addFocus}><Play size={16}/> Registrar sesión</button></div></div><div className="sectionTitle"><h2>Lectura</h2><span>{books.filter(b=>b.status==="finished").length} terminados</span></div><div className="bookList">{books.map(b=><article className="book" key={b.id} onClick={()=>logPages(b)}><Library/><div><b>{b.title}</b><small>{b.status==="finished"?"Terminado":b.total_pages?b.current_page+" / "+b.total_pages+" páginas":b.current_page+" páginas leídas"}</small></div><ChevronRight size={16}/></article>)}</div><div className="add"><input value={bookTitle} onChange={e=>setBookTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addBook()} placeholder="Añadir libro..."/><button onClick={addBook}><Plus/></button></div></section>}
 {tab==="Progreso"&&<><section className="hero"><div><span>NIVEL DE DISCIPLINA</span><strong>{pct}%</strong><small>{done}/{tasks.length} misiones · {workouts.filter(w=>w.completed).length} entrenos hoy</small></div><Trophy size={54}/></section><div className="stats"><Card icon={<Timer/>} title="Focus" text={focus.reduce((a,x)=>a+x.duration_minutes,0)+" min"}/><Card icon={<Library/>} title="Lectura" text={books.filter(b=>b.status==="finished").length+" libros terminados"}/><Card icon={<Dumbbell/>} title="Gym" text={workouts.filter(w=>w.completed).length+" sesiones hoy"}/><Card icon={<Flame/>} title="Misiones" text={pct+"% hoy"}/></div><div className="sectionTitle"><h2>Check-in diario</h2><span>{checkSaved?"Guardado":"Pendiente"}</span></div><section className="checkin"><BarChart3/><label>Sueño <b>{sleep} h</b><input type="range" min="3" max="12" step=".5" value={sleep} onChange={e=>{setSleep(Number(e.target.value));setCheckSaved(false)}}/></label><label>Energía <b>{energy}/10</b><input type="range" min="1" max="10" value={energy} onChange={e=>{setEnergy(Number(e.target.value));setCheckSaved(false)}}/></label><label>Ánimo <b>{mood}/10</b><input type="range" min="1" max="10" value={mood} onChange={e=>{setMood(Number(e.target.value));setCheckSaved(false)}}/></label><button className="primary" onClick={saveCheckin}>Guardar check-in</button></section><div className="sectionTitle"><h2>Despertar</h2><span>Rutina diaria</span></div><section className="wake"><Sunrise/><div><h2>Alarma inteligente</h2><p>Configura tu hora fija. La misión física avanzada se activará en la versión móvil nativa.</p></div><input type="time" value={alarm} onChange={e=>setAlarm(e.target.value)}/><label>Energía al despertar <b>{energy}/10</b><input type="range" min="1" max="10" value={energy} onChange={e=>setEnergy(Number(e.target.value))}/></label><button className="primary" onClick={saveSettings}>Guardar rutina</button></section></>}
 <nav>{[["Hoy",Home],["Hábitos",Target],["Gym",Dumbbell],["Estudio",BookOpen],["Progreso",Trophy]].map(([n,I]:any)=><button className={tab===n?"active":""} onClick={()=>setTab(n)} key={n}><I size={21}/><span>{n}</span></button>)}</nav></main>
}
function Title({done,total}:any){return <div className="sectionTitle"><h2>Misiones de hoy</h2><span>{done}/{total}</span></div>}
function TaskList({tasks,toggle}:any){return <section className="list">{tasks.map((t:Task)=><article className={"task "+(t.completed?"done":"")} key={t.id} onClick={()=>toggle(t)}><button className="check">{t.completed&&<Check size={15}/>}</button><div><b>{t.title}</b><small>{t.area}</small></div><ChevronRight size={17}/></article>)}</section>}
function Adder({input,setInput,add}:any){return <div className="add"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Añadir misión..."/><button onClick={add}><Plus/></button></div>}
function Card({icon,title,text}:any){return <article className="card"><i>{icon}</i><b>{title}</b><small>{text}</small></article>}
function Empty({icon,title,text,action}:any){return <section className="empty"><i>{icon}</i><h2>{title}</h2><p>{text}</p><span>{action}</span></section>}
function sub(t:string){return ({Hábitos:"Tu sistema diario de constancia.",Gym:"Hazte más fuerte cada semana.",Estudio:"Concéntrate. Aprende. Avanza.",Progreso:"Los números no mienten."} as any)[t]||""}
