"use client";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {Check,ChevronRight,Dumbbell,BookOpen,Flame,Home,Plus,Target,Trash2,Trophy,LogOut,LoaderCircle,Mail,Lock} from "lucide-react";
import {supabase} from "../lib/supabase";

type Task={id:string;title:string;completed:boolean;area:string|null};
const starter=[["Entrenamiento / fútbol","FOOTBALL"],["Estudiar 45 minutos","STUDY"],["Ducha fría","LIFE"],["Leer 10 páginas","LIFE"]];

export default function App(){
 const [tab,setTab]=useState("Hoy"),[tasks,setTasks]=useState<Task[]>([]),[input,setInput]=useState(""),[user,setUser]=useState<any>(null),[loading,setLoading]=useState(true);
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[authMsg,setAuthMsg]=useState(""),[authMode,setAuthMode]=useState<"login"|"signup">("login");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setUser(data.session?.user??null);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(user)loadTasks()},[user]);
 async function loadTasks(){const today=new Date().toISOString().slice(0,10);const {data}=await supabase.from("daily_tasks").select("id,title,completed,area").eq("task_date",today).order("position");if(data?.length)setTasks(data);else{const rows=starter.map(([title,area],i)=>({user_id:user.id,client_key:"starter-"+today+"-"+i,title,area,task_date:today,position:i}));const {data:fresh}=await supabase.from("daily_tasks").insert(rows).select("id,title,completed,area");setTasks(fresh??[])}}
 async function auth(){setAuthMsg("");const fn=authMode==="login"?supabase.auth.signInWithPassword({email,password}):supabase.auth.signUp({email,password});const {error}=await fn;if(error)setAuthMsg(error.message);else if(authMode==="signup")setAuthMsg("Cuenta creada. Si recibes un correo de confirmación, confírmalo y vuelve aquí.")}
 async function toggle(t:Task){const completed=!t.completed;setTasks(tasks.map(x=>x.id===t.id?{...x,completed}:x));await supabase.from("daily_tasks").update({completed}).eq("id",t.id)}
 async function add(){if(!input.trim())return;const today=new Date().toISOString().slice(0,10);const {data}=await supabase.from("daily_tasks").insert({user_id:user.id,client_key:"custom-"+crypto.randomUUID(),title:input.trim(),area:"LIFE",task_date:today,position:tasks.length}).select("id,title,completed,area").single();if(data)setTasks([...tasks,data]);setInput("")}
 async function remove(id:string){setTasks(tasks.filter(x=>x.id!==id));await supabase.from("daily_tasks").delete().eq("id",id)}
 const done=tasks.filter(t=>t.completed).length,pct=tasks.length?Math.round(done/tasks.length*100):0;
 if(loading)return <main className="auth"><LoaderCircle className="spin"/><p>Preparando LOCKED IN…</p></main>;
 if(!user)return <main className="auth"><div className="authLogo"><p className="eyebrow">LOCKED IN</p><h1>Tu disciplina.<br/>En un solo sitio.</h1><p className="muted">Entra para sincronizar tu progreso en todos tus dispositivos.</p></div><div className="authBox"><label><Mail size={17}/><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label><Lock size={17}/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&auth()}/></label><button className="primary" onClick={auth}>{authMode==="login"?"Entrar":"Crear cuenta"}</button>{authMsg&&<p className="authMsg">{authMsg}</p>}<button className="link" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"No tengo cuenta — crear una":"Ya tengo cuenta — entrar"}</button></div></main>;
 return <main className="shell"><header><div><p className="eyebrow">LOCKED IN</p><h1>{tab==="Hoy"?"Buenos días, Alex.":tab}</h1><p className="muted">{tab==="Hoy"?"Haz que hoy cuente.":sub(tab)}</p></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/></button></header>
 {tab==="Hoy"&&<><section className="hero"><div><span>PROGRESO DE HOY</span><strong>{pct}%</strong><small>{done} de {tasks.length} completadas</small></div><div className="ring" style={{"--p":pct} as CSSProperties}><b>{pct}</b></div></section><Title done={done} total={tasks.length}/><TaskList tasks={tasks} toggle={toggle}/><Adder input={input} setInput={setInput} add={add}/><div className="grid"><Card icon={<Dumbbell/>} title="Gym" text="Entrenamiento y progreso"/><Card icon={<BookOpen/>} title="Estudio" text="Sesiones y objetivos"/><Card icon={<Target/>} title="Disciplina" text="Hábitos y constancia"/><Card icon={<Trophy/>} title="Progreso" text={pct+"% completado hoy"}/></div></>}
 {tab==="Hábitos"&&<><Title done={done} total={tasks.length}/><section className="list">{tasks.map(t=><article className={"task "+(t.completed?"done":"")} key={t.id}><button className="check" onClick={()=>toggle(t)}>{t.completed&&<Check size={15}/>}</button><div onClick={()=>toggle(t)}><b>{t.title}</b><small>{t.area}</small></div><button className="delete" onClick={()=>remove(t.id)}><Trash2 size={17}/></button></article>)}</section><Adder input={input} setInput={setInput} add={add}/></>}
 {tab==="Gym"&&<Empty icon={<Dumbbell/>} title="Tu entrenamiento" text="Rutinas, ejercicios, pesos, repeticiones y evolución física quedarán registrados aquí." action="Base de Gym conectada"/>}
 {tab==="Estudio"&&<Empty icon={<BookOpen/>} title="Modo estudio" text="Organiza Universae, sesiones de concentración, apuntes y objetivos desde un solo sitio." action="Siguiente: Drive + focus"/>}
 {tab==="Progreso"&&<><section className="hero"><div><span>NIVEL DE DISCIPLINA</span><strong>{pct}%</strong><small>Basado en tus misiones de hoy</small></div><Trophy size={54}/></section><Empty icon={<Flame/>} title="Tu progreso" text="Aquí aparecerán rachas, estadísticas semanales, lectura y evolución de entrenamiento." action="Tus datos ya se guardan en la nube"/></>}
 <nav>{[["Hoy",Home],["Hábitos",Target],["Gym",Dumbbell],["Estudio",BookOpen],["Progreso",Trophy]].map(([n,I]:any)=><button className={tab===n?"active":""} onClick={()=>setTab(n)} key={n}><I size={21}/><span>{n}</span></button>)}</nav></main>
}
function Title({done,total}:any){return <div className="sectionTitle"><h2>Misiones de hoy</h2><span>{done}/{total}</span></div>}
function TaskList({tasks,toggle}:any){return <section className="list">{tasks.map((t:Task)=><article className={"task "+(t.completed?"done":"")} key={t.id} onClick={()=>toggle(t)}><button className="check">{t.completed&&<Check size={15}/>}</button><div><b>{t.title}</b><small>{t.area}</small></div><ChevronRight size={17}/></article>)}</section>}
function Adder({input,setInput,add}:any){return <div className="add"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Añadir misión..."/><button onClick={add}><Plus/></button></div>}
function Card({icon,title,text}:any){return <article className="card"><i>{icon}</i><b>{title}</b><small>{text}</small></article>}
function Empty({icon,title,text,action}:any){return <section className="empty"><i>{icon}</i><h2>{title}</h2><p>{text}</p><span>{action}</span></section>}
function sub(t:string){return ({Hábitos:"Tu sistema diario de constancia.",Gym:"Hazte más fuerte cada semana.",Estudio:"Concéntrate. Aprende. Avanza.",Progreso:"Los números no mienten."} as any)[t]||""}
