"use client";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {Check,ChevronRight,Dumbbell,BookOpen,Flame,Home,Plus,Target,Trash2,Trophy,LogOut,LoaderCircle,Mail,Lock} from "lucide-react";
import {supabase} from "../lib/supabase";

type Task={id:string;title:string;completed:boolean;area:string|null};
type Workout={id:string;title:string;completed:boolean;duration_minutes:number|null};
type Exercise={id:string;workout_id:string;name:string;sets:number|null;reps:string|null;weight_kg:number|null;completed:boolean};
const starter=[["Entrenamiento / fútbol","FOOTBALL"],["Estudiar 45 minutos","STUDY"],["Ducha fría","LIFE"],["Leer 10 páginas","LIFE"]];

export default function App(){
 const [tab,setTab]=useState("Hoy"),[tasks,setTasks]=useState<Task[]>([]),[input,setInput]=useState(""),[user,setUser]=useState<any>(null),[loading,setLoading]=useState(true);
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[authMsg,setAuthMsg]=useState(""),[authMode,setAuthMode]=useState<"login"|"signup">("login");
 const [workouts,setWorkouts]=useState<Workout[]>([]),[exercises,setExercises]=useState<Exercise[]>([]),[gymTitle,setGymTitle]=useState("Fuerza + potencia"),[exerciseName,setExerciseName]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setUser(data.session?.user??null);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(user){loadTasks();loadGym()}},[user]);
 async function loadGym(){const today=new Date().toISOString().slice(0,10);const {data:w}=await supabase.from("workouts").select("id,title,completed,duration_minutes").eq("workout_date",today).order("created_at");setWorkouts(w??[]);if(w?.length){const ids=w.map(x=>x.id);const {data:e}=await supabase.from("workout_exercises").select("id,workout_id,name,sets,reps,weight_kg,completed").in("workout_id",ids).order("position");setExercises(e??[])}else setExercises([])}
 async function createWorkout(){if(!gymTitle.trim())return;const {data}=await supabase.from("workouts").insert({user_id:user.id,title:gymTitle.trim(),kind:"GYM",workout_date:new Date().toISOString().slice(0,10),duration_minutes:60}).select("id,title,completed,duration_minutes").single();if(data)setWorkouts([...workouts,data])}
 async function addExercise(workoutId:string){if(!exerciseName.trim())return;const {data}=await supabase.from("workout_exercises").insert({user_id:user.id,workout_id:workoutId,name:exerciseName.trim(),sets:3,reps:"8-10",position:exercises.filter(e=>e.workout_id===workoutId).length}).select("id,workout_id,name,sets,reps,weight_kg,completed").single();if(data)setExercises([...exercises,data]);setExerciseName("")}
 async function toggleExercise(e:Exercise){const completed=!e.completed;setExercises(exercises.map(x=>x.id===e.id?{...x,completed}:x));await supabase.from("workout_exercises").update({completed}).eq("id",e.id)}
 async function finishWorkout(w:Workout){const completed=!w.completed;setWorkouts(workouts.map(x=>x.id===w.id?{...x,completed}:x));await supabase.from("workouts").update({completed}).eq("id",w.id)}
 async function loadTasks(){const today=new Date().toISOString().slice(0,10);const {data}=await supabase.from("daily_tasks").select("id,title,completed,area").eq("task_date",today).order("position");if(data?.length)setTasks(data);else{const rows=starter.map(([title,area],i)=>({user_id:user.id,client_key:"starter-"+today+"-"+i,title,area,task_date:today,position:i}));const {data:fresh}=await supabase.from("daily_tasks").insert(rows).select("id,title,completed,area");setTasks(fresh??[])}}
 async function auth(){setAuthMsg("");const fn=authMode==="login"?supabase.auth.signInWithPassword({email,password}):supabase.auth.signUp({email,password});const {error}=await fn;if(error)setAuthMsg(error.message);else if(authMode==="signup")setAuthMsg("Cuenta creada. Si recibes un correo de confirmación, confírmalo y vuelve aquí.")}
 async function toggle(t:Task){const completed=!t.completed;setTasks(tasks.map(x=>x.id===t.id?{...x,completed}:x));await supabase.from("daily_tasks").update({completed}).eq("id",t.id)}
 async function add(){if(!input.trim())return;const today=new Date().toISOString().slice(0,10);const {data}=await supabase.from("daily_tasks").insert({user_id:user.id,client_key:"custom-"+crypto.randomUUID(),title:input.trim(),area:"LIFE",task_date:today,position:tasks.length}).select("id,title,completed,area").single();if(data)setTasks([...tasks,data]);setInput("")}
 async function remove(id:string){setTasks(tasks.filter(x=>x.id!==id));await supabase.from("daily_tasks").delete().eq("id",id)}
 const done=tasks.filter(t=>t.completed).length,pct=tasks.length?Math.round(done/tasks.length*100):0;
 if(loading)return <main className="auth"><LoaderCircle className="spin"/><p>Preparando LOCKED IN…</p></main>;
 if(!user)return <main className="auth"><div className="authLogo"><p className="eyebrow">LOCKED IN</p><h1>Tu disciplina.<br/>En un solo sitio.</h1><p className="muted">Entra para sincronizar tu progreso en todos tus dispositivos.</p></div><div className="authBox"><label><Mail size={17}/><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label><Lock size={17}/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&auth()}/></label><button className="primary" onClick={auth}>{authMode==="login"?"Entrar":"Crear cuenta"}</button>{authMsg&&<p className="authMsg">{authMsg}</p>}<button className="link" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"No tengo cuenta — crear una":"Ya tengo cuenta — entrar"}</button></div></main>;
 return <main className="shell"><header><div><p className="eyebrow">LOCKED IN</p><h1>{tab==="Hoy"?"Buenos días, Alex.":tab}</h1><p className="muted">{tab==="Hoy"?"Haz que hoy cuente.":sub(tab)}</p></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/></button></header>
 {tab==="Hoy"&&<><section className="hero"><div><span>PROGRESO DE HOY</span><strong>{pct}%</strong><small>{done} de {tasks.length} completadas</small></div><div className="ring" style={{"--p":pct} as CSSProperties}><b>{pct}</b></div></section><Title done={done} total={tasks.length}/><TaskList tasks={tasks} toggle={toggle}/><Adder input={input} setInput={setInput} add={add}/><div className="grid"><Card icon={<Dumbbell/>} title="Gym" text="Entrenamiento y progreso"/><Card icon={<BookOpen/>} title="Estudio" text="Sesiones y objetivos"/><Card icon={<Target/>} title="Disciplina" text="Hábitos y constancia"/><Card icon={<Trophy/>} title="Progreso" text={pct+"% completado hoy"}/></div></>}
 {tab==="Hábitos"&&<><Title done={done} total={tasks.length}/><section className="list">{tasks.map(t=><article className={"task "+(t.completed?"done":"")} key={t.id}><button className="check" onClick={()=>toggle(t)}>{t.completed&&<Check size={15}/>}</button><div onClick={()=>toggle(t)}><b>{t.title}</b><small>{t.area}</small></div><button className="delete" onClick={()=>remove(t.id)}><Trash2 size={17}/></button></article>)}</section><Adder input={input} setInput={setInput} add={add}/></>}
 {tab==="Gym"&&<section className="gymPanel"><div className="sectionTitle"><h2>Entrenamiento de hoy</h2><span>{workouts.length} sesión{workouts.length===1?"":"es"}</span></div>{workouts.length===0?<div className="createWorkout"><Dumbbell size={36}/><h2>¿Qué toca hoy?</h2><p>Crea tu sesión y registra cada ejercicio.</p><input value={gymTitle} onChange={e=>setGymTitle(e.target.value)} placeholder="Nombre del entrenamiento"/><button className="primary" onClick={createWorkout}>Crear entrenamiento</button></div>:workouts.map(w=><article className={"workout "+(w.completed?"workoutDone":"")} key={w.id}><div className="workoutHead"><div><small>SESIÓN DE HOY</small><h2>{w.title}</h2><p>{w.duration_minutes??60} min · {exercises.filter(e=>e.workout_id===w.id&&e.completed).length}/{exercises.filter(e=>e.workout_id===w.id).length} ejercicios</p></div><button className="check big" onClick={()=>finishWorkout(w)}>{w.completed&&<Check/>}</button></div><div className="exerciseList">{exercises.filter(e=>e.workout_id===w.id).map(e=><div className={"exercise "+(e.completed?"done":"")} key={e.id} onClick={()=>toggleExercise(e)}><button className="check">{e.completed&&<Check size={14}/>}</button><div><b>{e.name}</b><small>{e.sets??3} series · {e.reps??"8-10"} reps{e.weight_kg?" · "+e.weight_kg+" kg":""}</small></div></div>)}</div><div className="add"><input value={exerciseName} onChange={e=>setExerciseName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addExercise(w.id)} placeholder="Añadir ejercicio..."/><button onClick={()=>addExercise(w.id)}><Plus/></button></div></article>)}</section>}
 {tab==="Estudio"&&<Empty icon={<BookOpen/>} title="Modo estudio" text="Organiza Universae, sesiones de concentración, apuntes y objetivos desde un solo sitio." action="Siguiente: Drive + focus"/>}
 {tab==="Progreso"&&<><section className="hero"><div><span>NIVEL DE DISCIPLINA</span><strong>{pct}%</strong><small>Basado en tus misiones de hoy</small></div><Trophy size={54}/></section><Empty icon={<Flame/>} title="Tu progreso" text="Aquí aparecerán rachas, estadísticas semanales, lectura y evolución de entrenamiento." action="Tus datos ya se guardan en la nube"/></>}
 <nav>{[["Hoy",Home],["Hábitos",Target],["Gym",Dumbbell],["Estudio",BookOpen],["Progreso",Trophy]].map(([n,I]:any)=><button className={tab===n?"active":""} onClick={()=>setTab(n)} key={n}><I size={21}/><span>{n}</span></button>)}</nav></main>
}
function Title({done,total}:any){return <div className="sectionTitle"><h2>Misiones de hoy</h2><span>{done}/{total}</span></div>}
function TaskList({tasks,toggle}:any){return <section className="list">{tasks.map((t:Task)=><article className={"task "+(t.completed?"done":"")} key={t.id} onClick={()=>toggle(t)}><button className="check">{t.completed&&<Check size={15}/>}</button><div><b>{t.title}</b><small>{t.area}</small></div><ChevronRight size={17}/></article>)}</section>}
function Adder({input,setInput,add}:any){return <div className="add"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Añadir misión..."/><button onClick={add}><Plus/></button></div>}
function Card({icon,title,text}:any){return <article className="card"><i>{icon}</i><b>{title}</b><small>{text}</small></article>}
function Empty({icon,title,text,action}:any){return <section className="empty"><i>{icon}</i><h2>{title}</h2><p>{text}</p><span>{action}</span></section>}
function sub(t:string){return ({Hábitos:"Tu sistema diario de constancia.",Gym:"Hazte más fuerte cada semana.",Estudio:"Concéntrate. Aprende. Avanza.",Progreso:"Los números no mienten."} as any)[t]||""}
